title: PALANTÍR
description: "Doppelkopf: Herr der Ringe Edition"
show_downloads: true
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme
github:
  zip_url: https://palantir.ladsko.de/PNG.zip
  another_url: another value
